---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
  - name: updated-weave-scope-release
  - name: version

outputs:
  - name: final-weave-scope-release

run:
  path: weave-scope-release/ci/tasks/commit-release-changes.sh
