---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
  - name: weave-scope-release

outputs:
  - name: candidate-release

run:
  dir: weave-scope-release
  path: weave-scope-release/ci/tasks/create-candidate.sh
