---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/pcf-ops
    tag: latest

inputs:
  - name: weave-scope-release
  - name: version

outputs:
  - name: final-weave-scope-release
  - name: final-release

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: weave-scope-release/ci/tasks/create-final.sh
