---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/weave-scope-release
    tag: acceptance-tests

inputs:
  - name: weave-scope-release
  - name: candidate-release
  - name: version

outputs:
  - name: bumped-version
  - name: final-weave-scope-release

params:
  BLOBSTORE_ACCESS_KEY_ID: replace-me
  BLOBSTORE_SECRET_ACCESS_KEY: replace-me

run:
  path: weave-scope-release/ci/tasks/finalize-release.sh
