---
platform: linux

image_resource:
  type: registry-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: weave-scope-release
  - name: concourse-bosh-deployment

run:
  path: weave-scope-release/ci/tasks/smoke-test-local.sh
