---
releases:
- name: weave-scope
  version: 0.0.9

addons:
- name: scope-probe
  jobs:
  - name: scope_probe
    release: weave-scope
    consumes:
      scope_app:
        from: scope_app
        deployment: weave-scope
- name: scope-garden
  include:
    jobs:
    - name: garden
      release: garden-runc
  jobs:
  - name: scope_garden
    release: weave-scope
    properties:
      weave:
        scope:
          probe:
            garden:
              network: tcp
              addr: 127.0.0.1:7777
            cf:
              api_url: https://api.bosh-lite.com
              client_id: admin-ro
              client_secret: admin-ro-secret
              skip_ssl_verify: true
