releases:
- name: weave-scope
  version: 0.0.5

addons:
- name: scope-probe
  jobs:
  - name: scope_probe
    release: weave-scope
  properties:
    weave:
      scope:
        probe:
          target_addr: 10.244.5.4
