---
name: scope-app
director_uuid: <BOSH-DIRECTOR-UUID>
releases:
- name: weave-scope
  version: latest
stemcells:
- alias: <STEMCELL-NAME>
  os: <STEMCELL-OS>
  version: latest
instance_groups:
- name: scope_app
  azs:
  - <SCOPE-APP-AZ>
  instances: 1
  lifecycle: service
  jobs:
  - name: scope_app
    release: weave-scope
    consumes: {}
    provides: {}
  vm_type: <SCOPE-APP-VM-TYPE>
  stemcell: <STEMCELL-NAME>
  properties: {}
  update:
    serial: true
    max_in_flight: 1
  networks:
  - name: <SCOPE-APP-NETWORK>
    default:
    - dns
    - gateway
  persistent_disk_type: '1024'
  vm_extensions: []
update:
  canaries: 1
  canary_watch_time: 30000-300000
  update_watch_time: 30000-300000
  max_in_flight: 1
  max_errors: 2
  serial: true
