addons:
- jobs:
  - consumes:
      weave_scope_app:
        deployment: weave-scope
        from: weave_scope_app
    name: scope_probe
    release: weave-scope
  name: scope-probe
- include:
    jobs:
    - name: garden
      release: garden-runc
  jobs:
  - name: scope_garden
    properties:
      weave:
        scope:
          probe:
            concourse:
              atc_password: admin
              atc_url: http://10.244.15.2:8080
              atc_username: admin
            garden:
              addr: 127.0.0.1:7777
              network: tcp
    release: weave-scope
  name: scope-garden
releases:
- name: weave-scope
  version: 0.17.7
