---
resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: "0.11.10"

resources:
  - name: weave-scope-release
    icon: github-circle
    type: git
    source:
      uri: git@github.com:EngineerBetter/weavescope-boshrelease.git
      branch: weavescope-ci
      private_key: ((github_private_key))
      ignore_paths:
        - .final_builds/
        - releases/
        - manifests/
        - docs/

  - name: version
    icon: tag
    type: semver
    source:
      key: version
      << : &candidate-s3-creds
        bucket: weave-scope-releases
        access_key_id: ((concourse_ci_s3_access_key))
        secret_access_key: ((concourse_ci_s3_secret_key))
        region_name: eu-central-1

  - name: final-release
    icon: file-cloud
    type: s3
    source:
      regexp: "weave-scope-final-release-(.*).tgz"
      << : *candidate-s3-creds

  - name: ci-tf
    icon: terraform
    type: terraform
    source:
      terraform_source: weave-scope-release/ci/tf/
      storage:
        bucket: weave-scope-ci
        bucket_path: /terraform/
        access_key_id: ((concourse_ci_s3_access_key))
        secret_access_key: ((concourse_ci_s3_secret_key))
        region_name: eu-central-1
        server_side_encryption: AES256
      env:
        AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
        AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
        AWS_DEFAULT_REGION: eu-central-1

jobs:
  - name: create-buckets
    serial: true
    plan:
    - get: weave-scope-release
      trigger: true
    - put: ci-tf
      params:
        env_name: whevs

  - name: unit-test-candidate-release
    plan:
      - get: weave-scope-release
        trigger: true
        passed: [create-buckets]
      - task: create-candidate-release
        file: weave-scope-release/ci/tasks/create-candidate.yml

  - name: acceptance-test-candidate-release
    plan:
      - get: weave-scope-release
        passed: [unit-test-candidate-release]
        trigger: true
      - task: create-candidate-release
        file: weave-scope-release/ci/tasks/create-candidate.yml

  - name: create-final-release
    serial: true
    serial_groups:
      - version
    plan:
      - in_parallel:
          - get: weave-scope-release
            passed: [acceptance-test-candidate-release]
            trigger: true
          - get: version
            params:
              bump: patch
      - task: create-final-release
        file: weave-scope-release/ci/tasks/create-final.yml
        params:
          BLOBSTORE_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
          BLOBSTORE_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
      - task: commit-release-changes
        file: weave-scope-release/ci/tasks/commit-release-changes.yml
      - put: final-release
        params:
          file: final-release/weave-scope-final-release-*.tgz
          acl: public-read
      - put: weave-scope-release
        params:
          repository: final-weave-scope-release
      - put: version
        params:
          file: version/version

  - name: bump-minor
    serial: true
    serial_groups:
      - version
    plan:
      - put: version
        params:
          bump: minor

  - name: bump-major
    serial: true
    serial_groups:
      - version
    plan:
      - put: version
        params:
          bump: major
