---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: "0.11.10"

resources:
- name: weave-scope-release
  type: git
  source:
    uri: git@github.com:EngineerBetter/weavescope-boshrelease.git
    branch: master
    private_key: ((github_deployment_key))
- name: version
  type: semver
  source:
    key: version
    << : &candidate-s3-creds
      bucket: ((candidate_release_bucket))
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
- name: candidate-release
  type: s3
  source:
    versioned_file: "weave-scope-dev-release.tgz"
    << : *candidate-s3-creds
- name: ci-tf
  type: terraform
  source:
    terraform_source: weave-scope-release/ci/tf/
    storage:
      bucket: weave-scope-ci
      bucket_path: /terraform/
      access_key_id: ((concourse_ci_s3_access_key))
      secret_access_key: ((concourse_ci_s3_secret_key))
      region_name: eu-central-1
      server_side_encryption: AES256
    env:
      AWS_ACCESS_KEY_ID: ((concourse_ci_s3_access_key))
      AWS_SECRET_ACCESS_KEY: ((concourse_ci_s3_secret_key))
      AWS_DEFAULT_REGION: eu-central-1

jobs:
- name: create-buckets
  serial: true
  plan:
  - get: weave-scope-release
    trigger: true
  - put: ci-tf

- name: create-release
  plan:
    - get: weave-scope-release
      trigger: true
      passed: [create-buckets]
    - task: create
      file: weave-scope-release/ci/tasks/create-candidate.yml
    - put: candidate-release
      params:
        file: "release/weave-scope-dev-release.tgz"

- name: finalize-release
  serial_groups:
    - version
  plan:
    - aggregate:
      - get: weave-scope-release
        passed: [create-release]
      - get: candidate-release
        passed: [create-release]
      - get: version
    - task: finalize-release
      file: weave-scope-release/ci/tasks/finalize-release.yml
      params:
        BLOBSTORE_ACCESS_KEY_ID: ((release_blobs_access_key_id))
        BLOBSTORE_SECRET_ACCESS_KEY: ((release_blobs_secret_access_key))
    - put: version
      params:
        bump: minor
    - put: weave-scope-release
      params:
        rebase: true
        repository: final-weave-scope-release
